### ISSUE TITLE
Match on only some 16bit unicode characters

### ISSUE THREAD

**Issue by glennpierce** [Alexhuszagh/rust-nom-unicode#1]
Hi I was hoping to ask some advice for using you library
I have to pass a uri string for the zinc file format
https://www.project-haystack.org/doc/Zinc
The BNF grammar for the uri is

<uri>         := "`" <uriChar>* "`"
<uriChar>     := <unicodeChar> | <uriEscChar>
<unicodeChar> := any 16-bit Unicode char >= 0x20 (except str/uri quote)
<uriEscChar>  := "\:" | "\/" | "\?" | "\#" | "\[" | "\]" | "\@" | "\`" | "\\" | "\&" | "\=" | "\;" | <uEscChar>
<uEscChar>    := "\u" <hexDigit> <hexDigit> <hexDigit> <hexDigit>

Now I can detect the additional uriEscChar values that the string can contain 
but how can I keep to unicode characters >= 0x20 (except str/uri quote)

Having trouble knowing where to start implementing that function.

Thanks

**Comment by Alexhuszagh** [comment]
@glennpierce Sorry for the delay, I was taking a break for open source work for personal reasons. An example of doing this would be simply:

```rust
#[macro_use]
extern crate nom;

/// """
fn quote(i: &str) -> nom::IResult<&str, char> {
    char!(i, '"')
}

/// any 16-bit Unicode char >= 0x20 (except str/uri quote)
fn uri_char(i: &str) -> nom::IResult<&str, char> {
    nom::character::complete::satisfy(|c| {
        let code = c as u32;
        !(code < 0x20 || c == '"')
    })(i)
}

named!(uri_chars<&str, Vec<char>>, many0!(
    uri_char
));

/// Parse a URI using the grammar above.
fn uri(i: &str) -> nom::IResult<&str, String> {
    let (i, _) = quote(i)?;
    let (i, value) = uri_chars(i)?;
    let (i, _) = quote(i)?;
    Ok((i, value.iter().cloned().collect()))
}

fn main() {
    println!("{:?}", uri("hello"));
    println!("{:?}", uri("\"real sample\""));
}
```

Notice how nom-unicode is never used here: that's intentional. nom-unicode intends to provide classification and parsing for unicode-aware codepoints, and this is much more basic and general. Also note that the `'|'`, `"\u"`. and ` ":" | "/" | "?" | "#" | "[" | "]" | "@" | "`" | "\" | "&" | "=" | ";"` are all redudant with "any >= 0x20 (except str/uri quote)", so they've been omitted. If not, you could use `alt!`.
